### ISSUE TITLE
add Thunderdome ENVIRONMENTAL METHODS OF MURDER

### ISSUE THREAD

**Issue by OtherwiseJunk** [OtherwiseJunk/TheDeepState#30]
do it coward

**Comment by OtherwiseJunk** [comment]
Examples

Chased off a cliff by a swarm of Japanese Murder Hornets
Tripped while descending down a steep slope, breaking {Random Number between 17-37} bones.
Fell into a trap set by {Surviving Tribute} while being chased by a bear.
Shot by Donald Trump Jr., who took {Pronoun, Their if unknown} head and pelt as a trophy.

**Comment by dninemfive** [comment]
Burned alive by an unseasonable wildfire
Struck by lighting
[all of the minecraft death messages]
Fatally injured by an equipment malfunction (maybe select pieces of equipment to malfunction)
